---
# Run Kubernetes 

# Kick off cluster from master
- name: Start the cluster
  become: yes
  shell: kubeadm init --pod-network-cidr=10.20.2.0/22 >> cluster.txt
  args:
    chdir: $HOME
    creates: cluster.txt

- name: Create .kube directory
  become: yes
  become_user: "{{ kube_user }}"
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to kube config
  become: yes
  shell: cp /etc/kubernetes/admin.conf {{ kube_home }}/.kube/config && chown {{ kube_user }} {{ kube_home }}/.kube/config

- name: Install Pod network using Flannel
  shell: kkubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_setup.txt 
  args:
    chdir: $HOME
    creates: pod_setup.txt

# Now add the workers

